### ISSUE TITLE
`ctrl-enter` to cycle between TODO and DONE should be `cmd+enter` for mac

### ISSUE THREAD

**Issue by cccntu** [athensresearch/athens#824]
**Problem**
In the welcome page:
> `ctrl-enter` to cycle between TODO and DONE

should be:

> `cmd-enter` to cycle between TODO and DONE

**Screenshots/Demo**

**Athens Version**
1.0.0-beta.56

**Comment by jasonminsookim** [comment]
Mine works with cmd-enter. I don't think this is an issue, at least with Beta 60

**Comment by sid597** [comment]
@cccntu works fine on ubuntu, beta.89, what os are you on?

**Comment by cccntu** [comment]
This was a doc issue, not sure if it fixed now.

In mac, the binding is actually `cmd-enter`, but in the welcome page it says `ctrl-enter `

**Comment by sid597** [comment]
@cccntu Thank you for clarifying that, yeah this is still an issue. We will update the welcome page doc to include both `ctrl` and `cmd`.
